// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsr82IVLYveWUWZUUksvJwKF_B_NgGME',
    appId: '1:651617072295:web:4a825f3f8b102311a99782',
    messagingSenderId: '651617072295',
    projectId: 'kaay-livrer-8171a',
    authDomain: 'kaay-livrer-8171a.firebaseapp.com',
    storageBucket: 'kaay-livrer-8171a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdo2u-H-UvZyD2MsCaz4dYpV30Stw5uow',
    appId: '1:651617072295:android:034e8a7e8dc0c723a99782',
    messagingSenderId: '651617072295',
    projectId: 'kaay-livrer-8171a',
    storageBucket: 'kaay-livrer-8171a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApMZq9qjAEq1cevLaIzYWtxfBKk10561U',
    appId: '1:651617072295:ios:1afd07c6faf535f5a99782',
    messagingSenderId: '651617072295',
    projectId: 'kaay-livrer-8171a',
    storageBucket: 'kaay-livrer-8171a.appspot.com',
    iosClientId: '651617072295-k3235ilpl0jrgevrq0ec5pa671v4f52g.apps.googleusercontent.com',
    iosBundleId: 'com.kaaygroup.kaayLivrer',
  );
}
